version: "3"
services:
  sonarqube:
    image: sonarqube:community
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL:-jdbc:postgresql://db:5432/sonar}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME:-sonar}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD:-sonar}
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SONAR_POSTGRES_USER:-sonar}
      POSTGRES_PASSWORD: ${SONAR_POSTGRES_PASSWORD:-sonar}
      POSTGRES_DB: ${SONAR_POSTGRES_DB:-sonar}
    volumes:
      - ./data/postgresql_home:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data

