#!/bin/bash

# cd to units directory
cd "$(dirname `readlink -f "$0"`)"

info_short()
{
  echo "Static code analyzer web service covers majority of programming languages"
}

init()
{
  mkdir -p ./data/sonarqube/{data,extensions,logs}
  chmod 777 ./data/sonarqube/{data,extensions,logs}
}

source ../.expo_functions
