#!/bin/bash

cd "$(dirname `readlink -f "$0"`)"

units_list()
{
  _rh_try_ret_help 'List all units'
  for d in units/*
  do
    if [ -f $d/docker-compose.yml ]
    then
      echo ${d:6:999}
    fi
  done
}

units_info()
{
  units_list | while read u
  do
    info=""
    if [ -f units/$u/expo ]
    then
      info=$(units/$u/expo info_short)
    fi
    if [ ! -z "$info" ]
    then
      echo "$u - $info"
    else
      echo "$u"
    fi
  done
}

unit()
{
  _rh_try_ret_help 'Manage single unit'

  if [ 0 == $# ]
  then
    echo "Specify a unit. Call units_list to list units"
    exit 1
  fi

  if [ ! -f units/$1/docker-compose.yml ]
  then
    echo "Unit $1 does not exists"
    exit 2
  fi

  cd units/
  unit=$1
  shift

  if [ -f $unit/expo ]
  then
    $unit/expo "$@"
  else
    cd $unit
    source ../../.expo_functions "$@"
  fi
}

ips()
{
  _rh_try_ret_help 'Print the ip adresses of running containers'
  docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}' | sed 's#^/##';
}

fix_perms()
{
  _rh_try_ret_help 'Fix the permissions of the repo'
  chmod 755 ./units/*/expo
}

gen_gitlab_ci()
{
  _rh_try_ret_help 'Generate gitlab ci with all discoverable units'

{
cat << EOF
stages:
  - create
  - purge

variables:
  BUILD_IMAGE: build-image:latest

.unit-create:
  stage: create
  image: \$BUILD_IMAGE
  when: manual
  script: ./expo unit \$UNIT up

.unit-purge:
  stage: purge
  image: \$BUILD_IMAGE
  when: manual
  script: ./expo unit \$UNIT purge

EOF

for u in $(units_list)
do
  cat << EOF
${u}-create:
  extends: .unit-create
  variables:
    UNIT: $u

${u}-purge:
  extends: .unit-purge
  variables:
    UNIT: $u

EOF

done

} > .gitlab-ci.yml

}

source ./.expo_functions
