#!/bin/bash

# cd to units directory
cd "$(dirname `readlink -f "$0"`)"

info_short()
{
  echo "Notification relay server from REST applications to android or websocket clients."
}

source ../.expo_functions
