services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123
