#!/bin/bash

# cd to units directory
cd "$(dirname `readlink -f "$0"`)"

info_short()
{
  echo "Deluxe latency measurement tool. It can measure, store and display latency, latency distribution and packet loss."
}

source ../../.expo_functions
