#!/bin/bash

# cd to units directory
cd "$(dirname `readlink -f "$0"`)"

info_short()
{
  echo "Monitoriung platform"
}

# no data folder needed
init()
{
  mkdir -p ./data/
  chmod 777 -R ./data/
}

source ../../.expo_functions
