services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      - GITLAB_ROOT_PASSWORD=$GITLAB_ROOT_PASSWORD:-@Password123}
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab'"
    ports:
      - 80
      - 443
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './data/gitlab-runner:/etc/gitlab-runner'
