#!/bin/bash

# cd to units directory
cd "$(dirname `readlink -f "$0"`)"

info_short()
{
  echo "Local VOD media server"
}

# no data folder needed
init()
{
  mkdir -p ./data/{metadata,config}
  chmod 777 -R ./data/
}

source ../.expo_functions
